"""
"BIBLIA - Book Index, Bibliography, & Literary Information Archive" / "BIBLIA - Buch-Index, Bibliografie, & Literarisches Informations-Archiv" version 1.0
Copyright (C) 2026  Nerdo3000

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import locale
if "de_" == locale.getlocale()[0][:3]:
    ANALYSIS_SUM = "Summe:"
    ANALYSIS_ARITH = "Arith. M.:"
    ANALYSIS_MEDIAN = "Median:"
    ANALYSIS_MIN = "Minimum:"
    ANALYSIS_MAX = "Maximum:"
    ANALYSIS_MOD = "Modus:"
    ANALYSIS_HEAD = "Auswertung der Werte:"
    #################################
    TOOLTIP_BIG_SMALL = "Soll Groß- und Kleinschreibung beim suchen ignoriert werden?"
    TOOLTIP_ALL_OR_ANY = "Vergleichbar mit einem logischen UND oder ODER: Müssen ALLE oder (mindestens) EIN Parameter übereinstimmen?"
    TOOLTIP_DELETE_SINGLE = "Dieser Eintrag wird Gelöscht"
    TOOLTIP_DELETE_SELECTION = "ALLE Einträge die im aktuellen Suchfilter sind werden GELÖSCHT"
    TOOLTIP_CLEAR_SEARCH_FILTER = "Alle Suchfilter löschen"
    TOOLTIP_TABLE = "Eine Tabelle der aktuellen Suchauswahl"
    TOOLTIP_ANALYSIS_HEAD = "Eine statistische Auswertung der Suchauswahl"
    TOOLTIP_BUTTON_ALL_LOCATIONS = "Alle Standorte anzeigen"
    TOOLTIP_IDX = "Index des aktuellen Eintrags"
    TOOLTIP_IDX_FRONT = "Erster Eintrag"
    TOOLTIP_IDX_L = "Vorheriger Eintrag"
    TOOLTIP_IDX_R = "Nächster Eintrag"
    TOOLTIP_IDX_BACK = "Letzter Eintrag"
    TOOLTIP_NEW_ENTRY = "Neuer Eintrag"
    TOOLTIP_EDITABLE = "Wenn aktiv, können Werte Programmweit nicht bearbeitet werden"
    TOOLTIP_SIMPLE_SEARCH = "Schnelle Suchfunktion: nicht sehr fein, aber schnell"
    TOOLTIP_CLEAR_SIMPLE_SEARCH = "Schnellsuche löschen"
    TOOLTIP_REGEX_ACTIVE = "Unterstützen die Parameter regex Suchen? (Für mehr Informationen gehe zu \"Über\" -> \"Regex\")"

    #################################
    NO_DATA_FOUND = "Keine Daten Gefunden"
    BIG_SMALL = "Groß- und Kleinschreibung ignorieren?"
    ALL_OR_ANY = "Alle Parameter müssen übereinstimmen?"
    REGEX_ACTIVE = "Regex suche?"
    DELETE_SINGLE = "Diesen Eintrag Löschen"
    DELETE_SELECTION = "Alle Einträge der Auswahl Löschen"
    CLEAR_SEARCH_FILTER = "Filter löschen"
    BUTTON_ALL_LOCATIONS = "Alle Standorte"
    ENTRY_NUMBER_TEXT = "Eintrag"
    NEW_ENTRY = "Neu"
    EDITABLE = "Schreibgeschützt?"
    BIBLIA_APP_NAME = "BIBLIA - Buch-Index, Bibliografie, & Literarisches Informations-Archiv"
    BIBLIA_APP_INFO = "Copyright Hinweis"
    BIBLIA_APP_REGEX_HEADER = "Regex Hilfe"
    BIBLIA_APP_REGEX_FILE_NAME = "./docs/about_regex_german.txt"
    BIBLIA_APP_DELETE = "Löschen"
    BIBLIA_APP_CANCEL = "Abbrechen"
    BIBLIA_APP_CLOSE = "Schließen"
    BIBLIA_APP_SAVE = "Speichern"
    BIBLIA_APP_NOT_CLOSE = "Nicht schließen"
    BIBLIA_APP_NOT_SAVE = "Nicht speichern"
    BIBLIA_APP_SAVE_QUESTION = "Vor dem Schließen speichern?"
    BIBLIA_APP_YOU_WANNA_REALY_DELETE = "Wollen Sie den Eintrag wirklich Löschen?\n Diese Aktion kann nicht Rückgängig gemacht werden"
    BIBLIA_APP_YOU_WANNA_REALY_DELETE_ALL = "Wollen Sie ALLE Einträge der aktuellen Auswahl wirklich Löschen?\n Diese Aktion ist EXTREM DESTRUKTIV und kann NICHT Rückgängig gemacht werden"
    BIBLIA_APP_YOU_WANNA_REALY_DELETE_ALL_FR = "Sind Sie sich wirklich wirklich Sicher?\nFolgende Einträge sind betroffen:"
    BIBLIA_APP_CONFIRM_DELETE = "Löschen Bestätigen"
    SIMPLE_SEARCH = "Einfache Suche:"

    #################################
    TAB_ENTRIES = "Eintragen"
    TAB_SEARCH = "Suchen"
    TAB_ANALYSIS = "Analysieren"
    TAB_LOCATION = "Standorte"
    #################################
    LAYOUTER_ADD_ENTRY = "Hinzufügen"
    LAYOUTER_TOOLTIP_SEARCH_SUBSTRING0 = "Nach "
    LAYOUTER_TOOLTIP_SEARCH_SUBSTRING2 = " suchen"
    LAYOUTER_CLEAR = "Löschen"
    LAYOUTER_TOOLTIP_POS_SUBSTRING0 = "Einträge in \""
    LAYOUTER_TOOLTIP_POS_SUBSTRING2 = "\" anzeigen"
    #################################
    MENU_EXPORT_ALL = "Exportieren"
    MENU_EXPORT_SELECT = "Exportieren (Auswahl)"
    MENU_EXPORT_SINGLE = "Exportieren (Eintrag)"
    MENU_IMPORT_EXCEL = "Excel CSV (International)::-IMPORT-"
    MENU_IMPORT_EXCEL_GERMAN = "Excel CSV (Deutsch)::-IMPORT-"
    MENU_GERMAN = "Deutsch"
    MENU_SAVE_MAIN = "Speichern::-SAVE_MAIN-"
    MENU_SAVE_AS = "Speichern unter::-SAVE_AS-"
    MENU_IMPORT = "Importieren"
    MENU_OPEN = "Öffnen::OPEN_FILE"
    MENU_FILE = "Datei"
    MENU_CLOSE = "Schließen::CLOSE"
    MENU_ABOUT = "Über"
    MENU_LIBS = "Bibliotheken"
else: 
    ANALYSIS_SUM = "Sum:"
    ANALYSIS_ARITH = "Arith. M.:"
    ANALYSIS_MEDIAN = "Median:"
    ANALYSIS_MIN = "Minimum:"
    ANALYSIS_MAX = "Maximum:"
    ANALYSIS_MOD = "Modus:"
    ANALYSIS_HEAD = "Analysis of the values:"
    #################################
    TOOLTIP_BIG_SMALL = "Should the search ignore upper and lower case?"
    TOOLTIP_ALL_OR_ANY = "Similar to a logical AND or OR: Do ALL or (at least) ONE parameter have to match?"
    TOOLTIP_DELETE_SINGLE = "This entry will be deleted"
    TOOLTIP_DELETE_SELECTION = "ALL entries that match the current search filter will be DELETED"
    TOOLTIP_CLEAR_SEARCH_FILTER = "Clear all search filters"
    TOOLTIP_TABLE = "A table of the current search selection"
    TOOLTIP_ANALYSIS_HEAD = "A statistical analysis of the values"
    TOOLTIP_BUTTON_ALL_LOCATIONS = "Show all locations"
    TOOLTIP_IDX = "Index of the current entry"
    TOOLTIP_IDX_FRONT = "First entry"
    TOOLTIP_IDX_L = "Previous entry"
    TOOLTIP_IDX_R = "Next entry"
    TOOLTIP_IDX_BACK = "Last entry"
    TOOLTIP_NEW_ENTRY = "New entry"
    TOOLTIP_EDITABLE = "When true, values across the app are not able to be edited"
    TOOLTIP_SIMPLE_SEARCH = "Simple search function: not very sophisticated, but simple"
    TOOLTIP_CLEAR_SIMPLE_SEARCH = "Clear simple search"
    TOOLTIP_REGEX_ACTIVE = "Do the search parameters accept regex search strings? (For more Information go to \"About\" -> \"Regex\")"

    #################################
    NO_DATA_FOUND = "No data was found"
    BIG_SMALL = "Ignore upper and lower case?"
    ALL_OR_ANY = "Do all the parameters have to match?"
    REGEX_ACTIVE = "Regex search?"
    DELETE_SINGLE = "Delete this entry"
    DELETE_SELECTION = "Delete all entries in the selection"
    CLEAR_SEARCH_FILTER = "Clear filter"
    BUTTON_ALL_LOCATIONS = "All locations"
    ENTRY_NUMBER_TEXT = "Entry"
    NEW_ENTRY = "New"
    EDITABLE = "Editable?"
    BIBLIA_APP_NAME = "Book Index, Bibliography, & Literary Information Archive"
    BIBLIA_APP_INFO = "Copyright notice"
    BIBLIA_APP_REGEX_HEADER = "Regex help"
    BIBLIA_APP_REGEX_FILE_NAME = "./docs/about_regex_english.txt"
    BIBLIA_APP_DELETE = "Delete"
    BIBLIA_APP_CANCEL = "Cancel"
    BIBLIA_APP_SAVE = "Save"
    BIBLIA_APP_CLOSE = "Close"
    BIBLIA_APP_NOT_CLOSE = "Don't close"
    BIBLIA_APP_NOT_SAVE = "Don't save"
    BIBLIA_APP_SAVE_QUESTION = "Save before closing?"
    BIBLIA_APP_YOU_WANNA_REALY_DELETE = "Are you sure you want to delete this entry?\n This action cannot be undone"
    BIBLIA_APP_CONFIRM_DELETE = "Confirm deletion"
    BIBLIA_APP_YOU_WANNA_REALY_DELETE_ALL = "Are you sure you want to delete ALL entries in the current selection?\n This action is EXTREMELY DESTRUCTIVE and CANNOT be undone"
    BIBLIA_APP_YOU_WANNA_REALY_DELETE_ALL_FR = "Are you really, really sure?\nThe following entries are affected:"
    SIMPLE_SEARCH = "Simple search"

    #################################
    TAB_ENTRIES = "Enter Data"
    TAB_SEARCH = "Search"
    TAB_ANALYSIS = "Analyse"
    TAB_LOCATION = "Locations"
    #################################
    LAYOUTER_ADD_ENTRY = "Add to list"
    LAYOUTER_TOOLTIP_SEARCH_SUBSTRING0 = "Search for "
    LAYOUTER_TOOLTIP_SEARCH_SUBSTRING2 = ""
    LAYOUTER_CLEAR = "Clear"
    LAYOUTER_TOOLTIP_POS_SUBSTRING0 = "Show entrys in \""
    LAYOUTER_TOOLTIP_POS_SUBSTRING2 = "\""
    #################################
    MENU_EXPORT_ALL = "Export"
    MENU_EXPORT_SELECT = "Export (selection)"
    MENU_EXPORT_SINGLE = "Export (entry)"
    MENU_IMPORT_EXCEL = "Excel CSV (International)::-IMPORT-"
    MENU_IMPORT_EXCEL_GERMAN = "Excel CSV (German)::-IMPORT-"
    MENU_GERMAN = "German"
    MENU_SAVE_MAIN = "Save::-SAVE_MAIN-"
    MENU_SAVE_AS = "Save as::-SAVE_AS-"
    MENU_IMPORT = "Import"
    MENU_OPEN = "Open::OPEN_FILE"
    MENU_FILE = "File"
    MENU_CLOSE = "Close::CLOSE"
    MENU_ABOUT = "About"
    MENU_LIBS = "Librarys"